apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-python-api
spec:
  replicas:  4
  selector:
    matchLabels:
      app: docker-k8s-python-api
  template:
    metadata:
      labels:
        app: docker-k8s-python-api
    spec:
      containers:
        - name: api
          image: docker-k8s-python-api-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
